apiVersion: v1
kind: Service
metadata:
  name: goldengate
  namespace: goldengate
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: goldengate
  sessionAffinity: None